### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tetraphobia** [r3valkyrie/yabin#1]
### Core Features

- [x] UI.

- [x] Create a paste.

- [x] View a paste.

- [ ] Set expire time.

- [ ] Set a title.

- [x] AES encryption.

- [ ] Encrypt/Decrypt client side, user-specified key.

- [ ] Documentation.

- [ ] View raw paste.

### Optional Features

- [ ] Manual syntax highlighting configuration.

- [ ] Vim and Emacs keybindings.

- [x] Docker support

- [ ] Fancy schmancy discord preview.

**Comment by tetraphobia** [comment]
See #2
