### ISSUE TITLE
Development Roadmap for March

### ISSUE THREAD

**Issue by tetraphobia** [r3valkyrie/yabin#2]
- [x] 0.1.0 - Basic functionality (UI, pasting).
- [x] 0.2.0 - Encryption.
- [x] 0.3.0 - Docker support.
- [ ] 0.4.0 - Titles, Discord embeds.
- [ ] 0.5.0 - Syntax highlighting.
- [ ] 1.0.0 - Initial release.
- [ ] 1.1.0 - CLI app
- [ ] 1.2.0 - Logins, paste history.
- [ ] 1.3.0 - Multiple pastes per ID
